In [5]:
#SuperVised-learning_to_calculate_vectors_for_word_embeddings
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding


In [6]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

In [7]:
sentiment=np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [8]:
one_hot("amazing resturant", 30)#it_will_assign_random_number_bw_1&_30_to_these_words

[22, 1]

In [9]:
one_hot("amazing resturant", 500)

[482, 259]

In [10]:
vocab_size=30
encoded_reviews=[one_hot(d, vocab_size) for d in reviews ]
encoded_reviews

[[4, 21],
 [22, 2],
 [1, 11],
 [5, 23, 16],
 [11, 20, 14],
 [26, 21],
 [4, 20, 8],
 [5, 10],
 [5, 7],
 [20, 17]]

In [11]:
#Padding_For_Making_The_vectors_of_equal_length
max_length=3
padded_reviews=pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[ 4, 21,  0],
       [22,  2,  0],
       [ 1, 11,  0],
       [ 5, 23, 16],
       [11, 20, 14],
       [26, 21,  0],
       [ 4, 20,  8],
       [ 5, 10,  0],
       [ 5,  7,  0],
       [20, 17,  0]], dtype=int32)

In [13]:
embedded_vector_size=5
model=Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_length, name='embedding'))#for_1st_embedded_layer
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [14]:
X=padded_reviews
y=sentiment

In [15]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              150       
                                                                 
 flatten (Flatten)           (None, 15)                0         
                                                                 
 dense (Dense)               (None, 1)                 16        
                                                                 
Total params: 166 (664.00 Byte)
Trainable params: 166 (664.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
model.fit(X, y, epochs=50, verbose=0)#Verbose_is_set_false_to_hide_epoch_computation_info

In [21]:
#Evaluate_model
loss, accuracy=model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 9ms/step - loss: 0.4436 - accuracy: 1.0000


1.0

In [22]:
#Evaluate_model
loss, accuracy=model.evaluate(X, y)
loss

1/1 [==============================] - 0s 11ms/step - loss: 0.4436 - accuracy: 1.0000


0.4435630738735199

In [24]:
model.get_layer('embedding').get_weights()[0]

array([[ 0.1825534 , -0.21911152, -0.17249988, -0.1608998 , -0.16496336],
       [ 0.18274324,  0.16353823, -0.19439805, -0.17540874,  0.15665843],
       [ 0.1476023 ,  0.1728453 ,  0.11559882,  0.1851431 ,  0.181751  ],
       [-0.03470908, -0.04357119, -0.03467516, -0.03068236,  0.00474074],
       [ 0.05031504,  0.06219621,  0.00832424, -0.04019628, -0.01264765],
       [-0.13582529, -0.22232957,  0.12806414,  0.14336565, -0.09900999],
       [ 0.02396112,  0.01299179,  0.04029833,  0.01589233, -0.02830607],
       [-0.13311222, -0.12261505, -0.17384198, -0.10526481, -0.1923112 ],
       [ 0.19324291, -0.240016  , -0.21360463, -0.18666849, -0.16946322],
       [-0.02026945,  0.03002366, -0.02842339, -0.00652082, -0.00353376],
       [-0.173257  , -0.15392695, -0.132953  , -0.15395372, -0.20356561],
       [ 0.13768479,  0.20584182, -0.00687439, -0.05568575,  0.15037666],
       [-0.03630307, -0.02107188, -0.01260407, -0.01122002, -0.00323556],
       [-0.02874338,  0.04194279, -0.0

In [25]:
weights=model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [26]:
weights[4]

array([ 0.05031504,  0.06219621,  0.00832424, -0.04019628, -0.01264765],
      dtype=float32)

In [27]:
weights[22]

array([ 0.16955525,  0.20508519, -0.15501311, -0.15286328,  0.14678931],
      dtype=float32)